apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2            # Tipo do EBS (gp2, io1, sc1, st1)
  fsType: ext4         # Tipo de sistema de arquivos
  encrypted: "true"    # Opcional: define se o volume EBS deve ser criptografado
  kmsKeyId: "your-kms-key-id"  # Opcional: KMS Key ID para criptografia personalizada
reclaimPolicy: Retain  # Política de retenção de volumes
volumeBindingMode: Immediate  # Modo de binding do volume (Immediate ou WaitForFirstConsumer)

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc  # Nome da StorageClass criada
  resources:
    requests:
      storage: 10Gi  # Tamanho do EBS que você deseja


